package utils

//Bitcoin Core 配置常量
const (
	RPCUSER     = "user"
	RPCPASSWORD = "pwd"
	RPCURL      = "http://127.0.0.1:8332"
	RPCVERSION  = "2.0"
)

//Bitcoin Core 常用命令常量
const (
	GETBESTBLOCKHASH             = "getbestblockhash"
	GETBLOCK                     = "getblock"
	GETBLOCKCHAININFO            = "getblockchaininfo"
	GETBLOCKCOUNT                = "getblockcount"
	GETBLOCKFILTER               = "getblockfilter"
	GETBLOCKHASH                 = "getblockhash"
	GETBLOCKHEADER               = "getblockheader"
	GETBLOCKSTATS                = "getblockstats"
	GETCHAINTIPS                 = "getchaintips"
	GETCHAINTXSTATS              = "getchaintxstats"
	GETDIFFICULTY                = "getdifficulty"
	GETMEMPOOLANCESTORS          = "getmempoolancestors"
	GETMEMPOOLDESCENDANTS        = "getmempooldescendants"
	GETMEMPOOLENTRY              = "getmempoolentry"
	GETMEMPOOLINFO               = "getmempoolinfo"
	GETRAWMEMPOOL                = "getrawmempool"
	GETTXOUT                     = "gettxout"
	GETTXOUTPROOF                = "gettxoutproof"
	GETTXOUTSETINFO              = "gettxoutsetinfo"
	PRECIOUSBLOCK                = "preciousblock"
	PRUNEBLOCKCHAIN              = "pruneblockchain"
	SAVEMEMPOOL                  = "savemempool"
	SCANTXOUTSET                 = "scantxoutset"
	VERIFYCHAIN                  = "verifychain"
	VERIFYTXOUTPROOF             = "verifytxoutproof"



	GETMEMORYINFO                = "getmemoryinfo"
	GETRPCINFO                   = "getrpcinfo"
	HELP                         = "help"
	LOGGING                      = "logging"
	STOP                         = "stop"
	UPTIME                       = "uptime"

	GENERATETOADDRESS            = "generatetoaddress"
	GENERATETODESCRIPTOR         = "generatetodescriptor"

	GETBLOCKTEMPLATE             = "getblocktemplate"
	GETMININGINFO                = "getmininginfo"
	GETNETWORKHASHPS             = "getnetworkhashps"
	PRIORITISETRANSACTION        = "prioritisetransaction"
	SUBMITBLOCK                  = "submitblock"
	SUBMITHEADER                 = "submitheader"

	ADDNODE                      = "addnode"
	CLEARBANNED                  = "clearbanned"
	DISCONNECTNODE               = "disconnectnode"
	GETADDEDNODEINFO             = "getaddednodeinfo"
	GETCONNECTIONCOUNT           = "getconnectioncount"
	GETNETTOTALS                 = "getnettotals"
	GETNETWORKINFO               = "getnetworkinfo"
	GETNODEADDRESSES             = "getnodeaddresses"
	GETPEERINFO                  = "getpeerinfo"
	LISTBANNED                   = "listbanned"
	PING                         = "ping"
	SETBAN                       = "setban"
	SETNETWORKACTIVE             = "setnetworkactive"




	ANALYZEPSBT                  = "analyzepsbt"
	COMBINEPSBT                  = "combinepsbt"
	COMBINERAWTRANSACTION        = "combinerawtransaction"
	CONVERTTOPSBT                = "converttopsbt"
	CREATEPSBT                   = "createpsbt"
	CREATERAWTRANSACTION         = "createrawtransaction"
	DECODEPSBT                   = "decodepsbt"
	DECODERAWTRANSACTION         = "decoderawtransaction"
	DECODESCRIPT                 = "decodescript"
	FINALIZEPSBT                 = "finalizepsbt"
	FUNDRAWTRANSACTION           = "fundrawtransaction"
	GETRAWTRANSACTION            = "getrawtransaction"
	JOINPSBTS                    = "joinpsbts"
	SENDRAWTRANSACTION           = "sendrawtransaction"
	SIGNRAWTRANSACTIONWITHKEY    = "signrawtransactionwithkey"
	TESTMEMPOOLACCEPT            = "testmempoolaccept"
	UTXOUPDATEPSBT               = "utxoupdatepsbt"

	CREATEMULTISIG               = "createmultisig"
	DERIVEADDRESSES              = "deriveaddresses"
	ESTIMATESMARTFEE             = "estimatesmartfee"
	GETDESCRIPTORINFO            = "getdescriptorinfo"
	SIGNMESSAGEWITHPRIVKEY       = "signmessagewithprivkey"
	VALIDATEADDRESS              = "validateaddress"
	VERIFYMESSAGE                = "verifymessage"



	ABANDONTRANSACTION           = "abandontransaction"
	ABORTRESCAN                  = "abortrescan"
	ADDMULTISIGADDRESS           = "addmultisigaddress"
	BACKUPWALLET                 = "backupwallet"
	BUMPFEE                      = "bumpfee"
	CREATEWALLET                 = "createwallet"
	DUMPPRIVKEY                  = "dumpprivkey"
	DUMPWALLET                   = "dumpwallet"
	ENCRYPTWALLET                = "encryptwallet"
	GETADDRESSESBYLABEL          = "getaddressesbylabel"
	GETADDRESSINFO               = "getaddressinfo"
	GETBALANCE                   = "getbalance"
	GETBALANCES                  = "getbalances"
	GETNEWADDRESS                = "getnewaddress"
	GETRAWCHANGEADDRESS          = "getrawchangeaddress"
	GETRECEIVEDBYADDRESS         = "getreceivedbyaddress"
	GETRECEIVEDBYLABEL           = "getreceivedbylabel"
	GETTRANSACTION               = "gettransaction"
	GETUNCONFIRMEDBALANCE        = "getunconfirmedbalance"
	GETWALLETINFO                = "getwalletinfo"
	IMPORTADDRESS                = "importaddress"
	IMPORTMULTI                  = "importmulti"
	IMPORTPRIVKEY                = "importprivkey"
	IMPORTPRUNEDFUNDS            = "importprunedfunds"
	IMPORTPUBKEY                 = "importpubkey"
	IMPORTWALLET                 = "importwallet"
	KEYPOOLREFILL                = "keypoolrefill"
	LISTADDRESSGROUPINGS         = "listaddressgroupings"
	LISTLABELS                   = "listlabels"
	LISTLOCKUNSPENT              = "listlockunspent"
	LISTRECEIVEDBYADDRESS        = "listreceivedbyaddress"
	LISTRECEIVEDBYLABEL          = "listreceivedbylabel"
	LISTSINCEBLOCK               = "listsinceblock"
	LISTTRANSACTIONS             = "listtransactions"
	LISTUNSPENT                  = "listunspent"
	LISTWALLETDIR                = "listwalletdir"
	LISTWALLETS                  = "listwallets"
	LOADWALLET                   = "loadwallet"
	LOCKUNSPENT                  = "lockunspent"
	REMOVEPRUNEDFUNDS            = "removeprunedfunds"
	RESCANBLOCKCHAIN             = "rescanblockchain"
	SENDMANY                     = "sendmany"
	SENDTOADDRESS                = "sendtoaddress"
	SETHDSEED                    = "sethdseed"
	SETLABEL                     = "setlabel"
	SETTXFEE                     = "settxfee"
	SETWALLETFLAG                = "setwalletflag"
	SIGNMESSAGE                  = "signmessage"
	SIGNRAWTRANSACTIONWITHWALLET = "signrawtransactionwithwallet"
	UNLOADWALLET                 = "unloadwallet"
	WALLETCREATEFUNDEDPSBT       = "walletcreatefundedpsbt"
	WALLETLOCK                   = "walletlock"
	WALLETPASSPHRASE             = "walletpassphrase"
	WALLETPASSPHRASECHANGE       = "walletpassphrasechange"
	WALLETPROCESSPSBT            = "walletprocesspsbt"

	GETZMQNOTIFICATIONS          = "getzmqnotifications"
)

const (
	FILEPATH = "./entity/blockChain.go"
)
